### PR TITLE
Price API and Invoice Items API

### PR DESCRIPTION
**Pull request by jramosg**

### CODE REVIEW

**Comment by bgalartza** [comment]
Hello! 
Thank you for adding the tests and squashing the commits.

For some reason the pipelines are not running for the pull requests (we need to give that a look), and we didn't realize that there is a mistake in the code (or maybe you forgot to commit that part):

The new `dev.gethop.payments.stripe.price` and `dev.gethop.payments.stripe.invoice-items` namespaces have to be required in the `dev.gethop.payments.stripe` namespace. This is required for the protocol to be extended correctly.

Once that is fixed we can accept and merge the commit.

Thank you again

Leaving the [previous PR](https://github.com/gethop-dev/payments.stripe/pull/14) here for reference

**Comment by jramosg** [comment]
Hello @bgalartza,

You are right, I already added the namespaces in a new commit. Do you again need to squash both commits in one?

Thank you

**Comment by bgalartza** [comment]
Yes, please.

Bear in mind that you don't need to open a new pull request if you don't want to. You can just `git push --force` in your repo/branch and the PR will be updated automatically.

**Comment by jramosg** [comment]
done! thank you

**Comment by jramosg** [comment]
done!

**Comment by bgalartza** [comment]
Great! 
Thank you for your time and work.

**Pull request merged**
